# Generated by Django 3.0.8 on 2020-08-28 17:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('amount', models.IntegerField(blank=True, default=1)),
                ('total_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiter_id', models.IntegerField()),
                ('table_name', models.CharField(max_length=10)),
                ('isitopen', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('meals', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm_app.Meal')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm_app.Table')),
            ],
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_categories', to='crm_app.Department')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='crm_app.MealCategory'),
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('servicefee', models.IntegerField()),
                ('totalsum', models.IntegerField()),
                ('meals', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='crm_app.Meal')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='crm_app.Order')),
            ],
        ),
    ]
