# Generated by Django 3.0.8 on 2020-09-04 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tebles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderedmeal',
            name='meal_id',
            field=models.ForeignKey(help_text="It's better to increase count than giving meal id twice or more", on_delete=django.db.models.deletion.CASCADE, to='crm_app.Meal'),
        ),
        migrations.AddField(
            model_name='orderedmeal',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderedmeals', to='crm_app.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm_app.Table'),
        ),
        migrations.AddField(
            model_name='order',
            name='waiter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealcategory',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_categories', to='crm_app.Department'),
        ),
        migrations.AddField(
            model_name='meal',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='crm_app.MealCategory'),
        ),
        migrations.AddField(
            model_name='check',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='crm_app.Order'),
        ),
    ]
