# Generated by Django 3.0.8 on 2020-08-30 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='date',
        ),
        migrations.RemoveField(
            model_name='check',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='meals',
        ),
        migrations.AlterField(
            model_name='check',
            name='servicefee',
            field=models.IntegerField(default=33),
        ),
        migrations.AlterField(
            model_name='order',
            name='isitopen',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='OrderedMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('count', models.IntegerField(blank=True, default=1)),
                ('total_sum', models.IntegerField(null=True)),
                ('meal_id', models.ForeignKey(help_text="It's better to increase count than giving mela id twice or more", on_delete=django.db.models.deletion.CASCADE, related_name='orderedmeals', to='crm_app.Meal')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderedmeals', to='crm_app.Order')),
            ],
        ),
    ]
