# Generated by Django 3.0.8 on 2020-08-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_auto_20200830_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedmeal',
            name='total_sum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
