# Generated by Django 3.0.8 on 2020-09-04 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_auto_20200904_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordercheck', to='crm_app.Order'),
        ),
    ]
