# Generated by Django 3.0.8 on 2020-08-30 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_auto_20200830_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedmeal',
            name='meal_id',
            field=models.ForeignKey(help_text="It's better to increase count than giving mela id twice or more", on_delete=django.db.models.deletion.CASCADE, to='crm_app.Meal'),
        ),
    ]
