# Generated by Django 3.0.8 on 2020-09-05 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_auto_20200904_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='servicefee',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.ServicePercentage'),
        ),
    ]
