# Generated by Django 3.0.8 on 2020-09-01 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_auto_20200901_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm_app.Table'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
