# Generated by Django 3.0.8 on 2020-09-01 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_auto_20200901_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='crm_app.Order'),
        ),
        migrations.AlterField(
            model_name='check',
            name='servicefee',
            field=models.IntegerField(default=33, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='totalsum',
            field=models.IntegerField(null=True),
        ),
    ]
