# Generated by Django 3.0.8 on 2020-09-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_auto_20200906_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isitopen',
            field=models.BooleanField(choices=[(1, True), (0, False)], default=1),
        ),
    ]
