# Generated by Django 3.0.8 on 2020-09-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_auto_20200901_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='totalsum',
            field=models.IntegerField(default=0),
        ),
    ]
