# Generated by Django 3.0.8 on 2020-09-07 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_auto_20200907_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_id',
            field=models.OneToOneField(error_messages={'invalid': 'order in this table is olready crated,use mealsToOrder to add meals'}, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm_app.Table'),
        ),
    ]
