# Generated by Django 3.0.8 on 2020-08-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
