# Generated by Django 3.0.8 on 2020-09-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_user', '0002_auto_20200905_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
