# Generated by Django 3.0.8 on 2020-09-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_user', '0003_auto_20200905_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='roleid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='crm_user.UserRole'),
        ),
    ]
