### Department
GET http://127.0.0.1:8000/departments/ HTTP/1.1

###
POST http://127.0.0.1:8000/departments/ HTTP/1.1
content-type: application/json

{
  "name": "bar"
}

###
DELETE http://127.0.0.1:8000/departments/1/ HTTP/1.1
