GET http://127.0.0.1:8000/meals/ HTTP/1.1

###
POST http://127.0.0.1:8000/meals/ HTTP/1.1
content-type: application/json

{
    "name": "cake",
    "category_id": 8,
    "price": 250,
    "description": ""
}
###
PUT http://127.0.0.1:8000/meals/ HTTP/1.1
content-type: application/json

{
  "id": 4,
  "name": "plov",
  "price": 250,
  "description": "dfghjkdfghjn"
}
###
DELETE http://127.0.0.1:8000/meals/8/ HTTP/1.1

###
GET http://127.0.0.1:8000/mealsByCategory/2/ HTTP/1.1