GET http://127.0.0.1:8000/meals/ HTTP/1.1

###
POST http://127.0.0.1:8000/meals/ HTTP/1.1
content-type: application/json

{
    "name": "lagman",
    "category_id": 8,
    "price": 410,
    "description": "lagman kol"
}
###
PUT http://127.0.0.1:8000/meals/ HTTP/1.1
content-type: application/json

{
  "id": 2,
  "name": "lagman",
  "price": 100,
  "description": "lagman is nices"
}
###
DELETE http://127.0.0.1:8000/meals/8/ HTTP/1.1

###
GET http://127.0.0.1:8000/mealsByCategory/4/ HTTP/1.1