GET http://127.0.0.1:8000/orders/ HTTP/1.1

###
POST http://127.0.0.1:8000/orders/ HTTP/1.1
content-type: application/json

{
    "table_id": 2,
    "orderedmeals" : [
        {
            "meal_id": 2,
            "name": "plov",
            "count": 2
        },
        {
            "meal_id": 1,
            "name": "cake",
            "count": 1
        }
    ]
}

###
DELETE http://127.0.0.1:8000/orders/1/ HTTP/1.1

###
GET http://127.0.0.1:8000/getopenstatus/ HTTP/1.1
