
GET http://127.0.0.1:8000/statuses/ HTTP/1.1

###
POST http://127.0.0.1:8000/statuses/ HTTP/1.1
content-type: application/json

{
  "name": "done"
}

###
DELETE http://127.0.0.1:8000/statuses/2/ HTTP/1.1


