### User
GET http://127.0.0.1:8000/users/ HTTP/1.1

### 
PUT  http://127.0.0.1:8000/users/ HTTP/1.1 
content-type: application/json

{
  "id": 3,
  "name": "Aidana",
  "surname": "Stalbekova",
  "email": "stalbekovaidana@example.com",
  "phone": "0551014345"
}

###
POST http://127.0.0.1:8000/users/ HTTP/1.1
content-type: application/json

{
  "name": "Aidana",
  "surname": "Stalbekova",
  "email": "aidana@gmail.com",
  "roleid": 2,
  "phone": "0777777777"
}

###
DELETE http://127.0.0.1:8000/users/3/ HTTP/1.1

###
POST http://127.0.0.1:8000/login/ HTTP/1.1
content-type: application/json

{
  "login":"Aidana_Stalbekova",
  "password":"0777777777"
}
